site:
  title: FlashLex Documentation
  start_page: flashlex-docs::index.adoc
content:
  sources:
  - url: .
    start_path: component
    branches: 
      - HEAD, dev
      - master
ui:
  bundle:
    url: ./ui/build/ui-bundle.zip
    snapshot: true

