site:
  title: FlashLex Documentation
  start_page: component-getting-started::index.adoc 
content:
  sources:
  - url: .
    start_path: component
    branches: HEAD
ui:
  bundle:
    url: ./ui/build/ui-bundle.zip
    snapshot: true

