version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.18
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/flashlex-docs
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Fallback cache to be used
            - v1-npm-deps-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: 
          name: Create Test Dir
          command: mkdir ~/flashlex-docs/junit
      - run:
          name: Test
          command: npm run test
          environment:
            MOCHA_FILE: ~/flashlex-docs/junit/test-results.xml
          when: always
      - store_test_results:
          path: ~/flashlex-docs/junit/test-results.xml
      - store_artifacts:
          path: ~/junit/test-results.xml
      - run:
          name: Antora Build
          command: npm run publish
      - aws-cli/install
      - run: aws --version
      - run:
          name: Deploy To S3
          command: bash scripts/copyweb.sh $(node iac/js/branchenv.js)

workflows:
  version: 2
  build_all:
    jobs:
      - build:
          filters:
            branches:
              only: 
              - dev
