@startuml flashlex-send-usecase
:IOT Device: as Thing
:IOT Backend: as IOTBackend
:FlashLex Cloud API: as API
:FlashLex SDK: as SDK

Thing->(Runs IOT Application)
SDK-->(Subscribe To Topic)
API-->(Publish To Topic)
API-->(Route REST to Topic)
(Runs IOT Application)-->(Subscribe To Topic)

IOTBackend-->(Manage Access Tokens)
IOTBackend-->(Send REST Messages)
API-->(Manage Access Tokens)
API-->(Recieve REST Messages)
@enduml